### ISSUE TITLE
[DISCUSSION] Release guidelines

### ISSUE THREAD

**Issue by cjnolet** [calrissian/mango#101]
We've been discussing the definitions for our release versions and I wanted to capture our working state here. This is original comment published by @eawagner:

Major release:
- Large addition of new functionality
- Major API changes (such as a project reorg)

Minor release:
- Any (non-major) API changes. i.e adding a utility method, adding a new TypeEncoder, or small refactoring efforts.
- Small additions of functionality. i.e. Changing the control flow of a utility function to provide additional functionality.

BugFix release:
- Only changes in functionality are to fix errors in the intended functionality of the existing code.
- Absolutely no public API changes. This means no new utility methods, typeencoders, changes to constants which are public (i.e. LEXI_TYPES).

As for deprecated apis, I am fine with waiting one minor release, but don't want to keep old code around much longer than that.

**Comment by cjnolet** [comment]
After some offline discussions, we've decided to accept semver (semver.org) as our versioning semantics. This is going to be accepted across Calrissian unless there are outstanding cases where it's not appropriate.

**Comment by eawagner** [comment]
We have gone through a few releases where we have adopted these patterns.  Closing the issue since it has worked.

We might want to document these outside of this ticket however so that others can perform releases for Calrissian projects in general.
