### ISSUE TITLE
More comprehensive Groovy DSL for Criteria, etc...

### ISSUE THREAD

**Issue by cjnolet** [calrissian/mango#115]
Groovy has a much more extensive support for DSLs than just what we've used in Calrissian. I'm thinking maybe there should be a mango-groovy module for the groovy DSL support. I think a more SQL-esque API could come much easier too:

select 'age', 'name' from 'entityStore' where "(('age' > 50) and ('name' == 'Jack'))";

Could parse out to be the following builder:

select('age', 'name').from('entityStore').where(and().gt('age', 50).eq('name', 'Jack'));

with minimal effort.

http://www.slideshare.net/glaforge/going-to-mars-with-groovy-domainspecific-languages

**Comment by eawagner** [comment]
While this is an interesting idea, we should look at this as an implementation option for #209 

I definitely agree Groovy would be an interesting option.
