### ISSUE TITLE
Consider having TupleStore extend google's ListMultimap interface

### ISSUE THREAD

**Issue by cjnolet** [calrissian/mango#140]
Most of the methods on this interface are already supplied but it will allow us to use other code from Google that works on ListMultimap.

**Comment by eawagner** [comment]
This will conflict with some of the concepts in the proposed 2.0.0 changes related to making these classes immutable.  For example, the add and remove methods.  

Instead I propose investigating providing accessor for an unmodifiable view of the underlying multimap backing these objects.

**Comment by cjnolet** [comment]
Can this be closed?

**Comment by eawagner** [comment]
Depends did you want to treat this as 'won't fix' or could there be some benefit to exposing the underlying multimap as an accessor?

**Comment by cjnolet** [comment]
I think for now we should close it as a wontfix. I don't have any immediate
for the mutlimap as an accessor.
