### ISSUE TITLE
Remove property file requirements from CanonicalizerContext

### ISSUE THREAD

**Issue by eawagner** [calrissian/mango#146]
Currently, this class requires that both a validator.properties and a canonicalDef.properties be present in order to correctly use these.  The worst part to this is that since, mango ships with a validator.properties file, this is the one that will always get picked up on the classpath first, meaning that we really only support two types of validation.

This class should work in a similar manner to the way the TypeEncoders class works allowing someone to programatically define their canonical context instead of through the use of these property files.

**Comment by cjnolet** [comment]
After some offline discussions, I'm fine deprecating this in < 2.0.0 releases and just removing post 2.0.0. This is something that can be useful but the implementation isn't really thatuseful.
