### ISSUE TITLE
Replace URIResolver API

### ISSUE THREAD

**Issue by eawagner** [calrissian/mango#148]
There are a few problems with the current URI Resolver API design which are suboptimal and would be very difficult to simply update through a normal deprecation/fix process.  For instance requiring that each resolver use a to and from stream method (Issue #113), the resolveUri requires and array of auths, or getServiceName should more properly be named getScheme.  

Additionally, the URIRegisty could work in a similar fashion to TypeRegistry encapsulating the logic around handling and calling the resolve methods on the correct resolver and providing an immutable container.

**Comment by cjnolet** [comment]
I'm fine deprecating this in < 2.0.0 and replacing in 2.0.0
