### ISSUE TITLE
Release Mango 1.4.0

### ISSUE THREAD

**Issue by cjnolet** [calrissian/mango#159]
Enhancements:

- Events now have type field
- Event extends Entity
- JsonTupleStore

**Comment by eawagner** [comment]
Actualy, only the JsonTupleStore is new for a 1.4.0.  The changes to Event made it into 1.3.0

**Comment by cjnolet** [comment]
So are we good to release this?

**Comment by eawagner** [comment]
Did you want to fix the Splitter.splitToList calls.  I think this is one of the things that breaks the 14.0.1 compatability.

**Comment by cjnolet** [comment]
Sure. how do you feel about deprecating the Tuple stuff in 1.4.0 so that we
can go clean in 2.0.0?
