### ISSUE TITLE
OSGi Support

### ISSUE THREAD

**Issue by skahmann** [calrissian/mango#163]
Would you be open to enabling OSGi support for the project? It's pretty easy to do with the maven-bundle-plugin. I can create a pull-request if required.

Thanks!

**Comment by eawagner** [comment]
Yes, I would definitely be open do it.  

It has been a while since I used the bundle-plugin, but we might need to be careful with the version policy for guava packages.  While we build against 15.0, I think we want to allow imports for other major versions.  Or alternatively, leave the versions off the guava import packages.

**Comment by skahmann** [comment]
I wouldn't leave the versions off as that can cause problems down the road, but you can easily provide versions or version ranges that are supported. I'm not very familiar with the project, but I can get a PR together if you'd like. Thank you!

**Comment by skahmann** [comment]
I created https://github.com/calrissian/mango/pull/164 to create OSGi bundle information. If you have specific version considerations for guava, you can add something like:
```xml
<Import-Package>com.google.common*;version="[15.0,17)",*</Import-Package>
```
More information about version strings [here](http://www.eclipse.org/virgo/documentation/virgo-documentation-3.6.0.M01/docs/virgo-user-guide/html/ch02s02.html).

Another thing to be careful about is to use [semantic versioning](http://semver.org/) for your bundles. Many people forget to increment the major version number when implementing a breaking change.

**Comment by eawagner** [comment]
Thanks, will look over the pull request tonight.

And I thought my days of working with OSGI headers were behind me :)
