### ISSUE TITLE
IP classes should be caching the byteArray used for comparisons instead of the InetAddress

### ISSUE THREAD

**Issue by eawagner** [calrissian/mango#183]
The reason for this is that every comparison uses the byte array from InetAddress.getAddress().  

The problem is that this method generates a new byte array for each address in the comparison.  This happens for every comparison, causing a lot of small byte arrays to get created on the heap.  It is better to simply cache the byte array to make the comparison operations faster.

**Comment by eawagner** [comment]
I would like to investigate this further, with good benchmarking.

**Comment by cjnolet** [comment]
LRUCache?

**Comment by eawagner** [comment]
I was thinking just to store the byte arrays as class variables, so that we didn't create new arrays every time toByteArray() was called.  Potentially, instead of storing the underlying InetAddress class, as that is simply redundant

That being said, the overhead of creating such small arrays is very small, so I want to run some benchmarks to see what the benefits are to different approaches.
