### ISSUE TITLE
CloseableIterables needs a toList() or toCollection method

### ISSUE THREAD

**Issue by cjnolet** [calrissian/mango#184]

**Comment by eawagner** [comment]
You an already do this with Lists.newArrayList(...) or Sets.newHashSet(...).  

CloseableIterables are designed to be able be iterated against multiple times so you could theoretically create multiple collections from the same data as long as you didn't close that Iterable.  If you only wanted one use however you could always do 
Lists.newArrayList(CloseableIterables.autoClose(...));

**Comment by eawagner** [comment]
I think we should close this.  I don't think CloseableIterables needs a dedicated method for this.
