### ISSUE TITLE
Fix use of methods that have been deprecated in new guava versions.

### ISSUE THREAD

**Issue by eawagner** [calrissian/mango#210]
We hit the fact that Iterators.emptyIterator() is no longer available after guava 20.

I think we should still probably stay compatible as far back as possible, but we should make sure we are still compatible with the latest version of guava.

**Comment by eawagner** [comment]
Do we want to change the default guava version to 20 or 21 for 2.0.0.

**Comment by vincentrussell** [comment]
What would be the reason to not go with the latest version?

**Comment by vincentrussell** [comment]
Oh... duh.. because Iterators.emptyIterator()

**Comment by eawagner** [comment]
I have updated master to use guava 20.0 and made sure it was compatible.  I have also made sure it was compatible back to guava 15.0, with most functionality (no IPv6) working with 14.0.

Guava 21.0 is only Java8 compatible, so I opened up a new ticket #211 for adding java 8 functionality, but figure that is a little out of scope for a 2.0.0 release which is long overdue.

**Comment by eawagner** [comment]
This update was also very very low impact.  Only use of the internal Iterators.emptyIterator were affected meaning no client code should be affected.

**Comment by vincentrussell** [comment]
awesome Alan.  sounds great.
